name: Release Apk Bundle

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Application version'
        required: true
        default: '1.0'
jobs:
  build:
    name: Build Signed APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'android_keystore.jks'
          fileDir: '/home/runner/work/<<project name>>/<<project name>>/app/keystore/'
          encodedString: ${{ secrets.KEYSTORE }}

      # Build and sign APK ("-x test" argument is used to skip tests)
      - name: Build APK
        run: ./gradlew :app:assembleRelease -x test
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      #rename apk to new Version
      - name: Change version APK
        run: [[ ${{ github.event.inputs.version }} != "1.0" ]] && mv app/build/outputs/apk/release/Zekrshomar_1.0.apk  app/build/outputs/apk/release/Zekrshomar_${{ github.event.inputs.version }}.apk

      # Save the APK after the Build job is complete to publish it as a Github release in the next job
      - name: Upload APK
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Zekrshomar
          path: app/build/outputs/apk/release/Zekrshomar_${{ github.event.inputs.version }}.apk



      - name: Build Bundle
        run: ./gradlew build

      - name: Assemble Release Bundle
        run: |
          ./gradlew bundleRelease
      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Change version Bundle
        run: mv app/build/outputs/bundle/release/app-release.aab  app/build/outputs/bundle/release/Zekrshomar_${{ github.event.inputs.version }}.aab

      - name: Upload APK
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Zekrshomar
          path: app/build/outputs/bundle/release/Zekrshomar_${{ github.event.inputs.version }}.aab


  release:
    name: Release APK
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: Zekrshomar
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          files: Zekrshomar/Zekrshomar_${{ github.event.inputs.version }}.apk &&  Zekrshomar/Zekrshomar_${{ github.event.inputs.version }}.aab