name: Android CI Rele

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Application version'
        required: true
        default: '1.0'
jobs:
  build:
    name: Build Signed APK
    runs-on: ubuntu-latest


#    steps:
#      - uses: r0adkll/sign-android-release@v1
#        name: Sign app APK
#        # ID used to access action output
#        id: sign_app
#        with:
#          releaseDirectory: app/build/outputs/apk/release
#          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
#          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
#          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
#          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
#        env:
#          # override default build-tools version (29.0.3) -- optional
#          BUILD_TOOLS_VERSION: "30.0.2"
#
#      # Example use of `signedReleaseFile` output -- not needed
#      - uses: actions/upload-artifact@v2
#        with:
#          name: Signed app bundle
#          path: ${{steps.sign_app.outputs.signedReleaseFile}}



    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease
      - name: Releasing using Hub
        uses: kyze8439690/action-release-releaseapk@master
        env:
             GITHUB_TOKEN: ${{ secrets.TOKEN }}
             APP_FOLDER: app



#      - uses: ilharp/sign-android-release@v1.0.4 # Or use @nightly
#        name: Sign app APK
#        id: sign_app
#        with:
#          releaseDir: app/build/outputs/apk/release
#          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
#          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
#          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
#          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
#          buildToolsVersion: 33.0.0
#
#      - uses: actions/upload-artifact@v3
#        with:
#          name: Signed app bundle
#          path: ${{steps.sign_app.outputs.signedFile}}



#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#           java-version: '17'
#           distribution: 'temurin'
#           cache: gradle
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Build APK
#        run: ./gradlew :app:assembleRelease -x test
#        env:
#          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
#          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
#          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
#
#
#      - name: Releasing using Hub
#        uses: VladDaniliuk/action-release-releaseapk@master
#        env:
#           GITHUB_TOKEN: ${{ secrets.TOKEN }}
#           VERSION_VARIABLE: versionName
##           APP_FILE: buildSrc/Android.kt
#           APP_FOLDER: app/build/outputs/apk/release/Zekrshomar.apk
##           CHANGELOG_FILE: ./CHANGELOG.md
##           RELEASE_TITLE: New Build
##           NAME_VARIABLE: app-release.apk
#
##      - uses: iota9star/sign-android-release@v1.0.5
##        name: Sign app APK
##          # ID used to access action output
##        id: sign_app
##        with:
##          releaseDirectory: app/build/outputs/apk/release
###          fileRex: .*apk
##          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
##          alias: ${{ secrets.ALIAS }}
##          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
##          keyPassword: ${{ secrets.KEY_PASSWORD }}
##        env:
##          BUILD_TOOLS_VERSION: "30.0.2"
#
#
#
##      - uses: r0adkll/sign-android-release@v1
##        name: Sign app APK
##        with:
##          releaseDirectory: app/build/outputs/apk/release
##          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
##          alias: ${{ secrets.ALIAS }}
##          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
##          keyPassword: ${{ secrets.KEY_PASSWORD }}
#
#
##      - uses: noriban/sign-android-release@v3
##        id: sign_app
##        with:
##          releaseDirectory: app/build/outputs/apk/release
##          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
##          alias: ${{ secrets.ALIAS }}
##          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
##          keyPassword: ${{ secrets.KEY_PASSWORD }}
##        env:
##          BUILD_TOOLS_VERSION: "30.0.2"
#
#
#
#      # Example use of `signedReleaseFile` output -- not needed
#      - uses: actions/upload-artifact@v2
#        with:
#          name: Signed app bundle
#          path: ${{steps.sign_app.outputs.signedReleaseFile}}

  release:
    name: Release APK
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: <<application name>>
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          files: <<application name>>/<<application name>>_${{ github.event.inputs.version }}.apk